# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x0fgrpc_playground\"L\n\x05Order\x12\x14\n\x0cinstrumentID\x18\x01 \x01(\x03\x12\r\n\x05price\x18\x02 \x01(\x03\x12\x10\n\x08quantity\x18\x03 \x01(\x03\x12\x0c\n\x04side\x18\x04 \x01(\x08\"\x1c\n\nOrderReply\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32Q\n\x0cOrderService\x12\x41\n\x08\x41\x64\x64Order\x12\x16.grpc_playground.Order\x1a\x1b.grpc_playground.OrderReply\"\x00\x62\x06proto3')



_ORDER = DESCRIPTOR.message_types_by_name['Order']
_ORDERREPLY = DESCRIPTOR.message_types_by_name['OrderReply']
Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:grpc_playground.Order)
  })
_sym_db.RegisterMessage(Order)

OrderReply = _reflection.GeneratedProtocolMessageType('OrderReply', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREPLY,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:grpc_playground.OrderReply)
  })
_sym_db.RegisterMessage(OrderReply)

_ORDERSERVICE = DESCRIPTOR.services_by_name['OrderService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDER._serialized_start=32
  _ORDER._serialized_end=108
  _ORDERREPLY._serialized_start=110
  _ORDERREPLY._serialized_end=138
  _ORDERSERVICE._serialized_start=140
  _ORDERSERVICE._serialized_end=221
# @@protoc_insertion_point(module_scope)
